services:
  - type: worker
    name: whatsapp-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    disk:
      name: wwebjs_auth
      mountPath: /data
      sizeGB: 1
